/**
 * generated by Xtext 2.12.0
 */
package org.evidently.ui.contentassist;

import org.evidently.ui.contentassist.AbstractEvidentlyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EvidentlyProposalProvider extends AbstractEvidentlyProposalProvider {
}
