/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class EvidentlyIdeaModule extends AbstractEvidentlyIdeaModule {
}
