/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class EvidentlyIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new EvidentlyStandaloneSetupIdea().createInjector
	}

}
