/*
 * generated by Xtext 2.12.0
 */
package org.evidently.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEvidentlyScopeProvider extends DelegatingScopeProvider {
}
