/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.evidently.idea.lang.EvidentlyLanguage

class EvidentlyCompletionContributor extends AbstractEvidentlyCompletionContributor {
	new() {
		this(EvidentlyLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
