/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractEvidentlyFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "evidently";

	protected AbstractEvidentlyFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Evidently files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Evidently";
	}

}
