/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class EvidentlyLanguage extends AbstractXtextLanguage {

	public static final EvidentlyLanguage INSTANCE = new EvidentlyLanguage();

	private EvidentlyLanguage() {
		super("org.evidently.Evidently");
	}

}
