/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea;

import org.evidently.idea.AbstractEvidentlyIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class EvidentlyIdeaModule extends AbstractEvidentlyIdeaModule {
}
