/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea;

import com.google.inject.Injector;
import org.evidently.EvidentlyStandaloneSetupGenerated;

@SuppressWarnings("all")
public class EvidentlyStandaloneSetupIdea extends EvidentlyStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from EvidentlyIdeaModule to Module");
  }
}
