/**
 * generated by Xtext 2.12.0
 */
package org.evidently.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.evidently.ui.AbstractEvidentlyUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EvidentlyUiModule extends AbstractEvidentlyUiModule {
  public EvidentlyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
