/**
 * generated by Xtext 2.12.0
 */
package org.evidently;

import org.evidently.EvidentlyStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EvidentlyStandaloneSetup extends EvidentlyStandaloneSetupGenerated {
  public static void doSetup() {
    new EvidentlyStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
