/*
 * generated by Xtext 2.12.0
 */
package org.evidently.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class EvidentlyWebModule extends AbstractEvidentlyWebModule {
}
