/*
 * generated by Xtext 2.12.0
 */
package org.evidently.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.evidently.ui.internal.EvidentlyActivator;

public class EvidentlyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EvidentlyActivator.getInstance().getInjector("org.evidently.Evidently");
	}

}
