/**
 * generated by Xtext 2.12.0
 */
package org.evidently.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.evidently.scoping.AbstractEvidentlyScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EvidentlyScopeProvider extends AbstractEvidentlyScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    System.out.println("GETSCIPE");
    return super.getScope(context, reference);
  }
}
