/**
 * generated by Xtext 2.12.0
 */
package org.evidently.scoping;

import org.evidently.scoping.AbstractEvidentlyScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EvidentlyScopeProvider extends AbstractEvidentlyScopeProvider {
}
