/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.highlighting;

import org.evidently.idea.highlighting.EvidentlyBaseColorSettingsPage;

@SuppressWarnings("all")
public class EvidentlyColorSettingsPage extends EvidentlyBaseColorSettingsPage {
}
