/**
 * generated by Xtext 2.12.0
 */
package org.evidently.ide;

import org.evidently.ide.AbstractEvidentlyIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EvidentlyIdeModule extends AbstractEvidentlyIdeModule {
}
