/**
 * generated by Xtext 2.12.0
 */
package org.evidently.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.evidently.EvidentlyRuntimeModule;
import org.evidently.EvidentlyStandaloneSetup;
import org.evidently.ide.EvidentlyIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EvidentlyIdeSetup extends EvidentlyStandaloneSetup {
  @Override
  public Injector createInjector() {
    EvidentlyRuntimeModule _evidentlyRuntimeModule = new EvidentlyRuntimeModule();
    EvidentlyIdeModule _evidentlyIdeModule = new EvidentlyIdeModule();
    return Guice.createInjector(Modules2.mixin(_evidentlyRuntimeModule, _evidentlyIdeModule));
  }
}
