/*
 * generated by Xtext 2.12.0
 */
package org.evidently


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvidentlyStandaloneSetup extends EvidentlyStandaloneSetupGenerated {

	def static void doSetup() {
		new EvidentlyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
