/*
 * generated by Xtext 2.12.0
 */
package org.evidently


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EvidentlyRuntimeModule extends AbstractEvidentlyRuntimeModule {
}
