/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlyPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public EvidentlyPomDeclarationSearcher() {
		super(EvidentlyLanguage.INSTANCE);
	}
}
