/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlyPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public EvidentlyPomDeclarationSearcher() {
		super(EvidentlyLanguage.INSTANCE);
	}
}
