/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.eclipse.xtext.xbase.idea.completion.XbaseCompletionContributor;

public class AbstractEvidentlyCompletionContributor extends XbaseCompletionContributor {
	public AbstractEvidentlyCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
