/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractEvidentlyCompletionContributor extends TerminalsCompletionContributor {
	public AbstractEvidentlyCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
