/*
 * generated by Xtext 2.12.0
 */
package org.evidently.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.evidently.ui.internal.EvidentlyActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvidentlyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EvidentlyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EvidentlyActivator.getInstance().getInjector(EvidentlyActivator.ORG_EVIDENTLY_EVIDENTLY);
	}
	
}
