/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.lang


class EvidentlyFileType extends AbstractEvidentlyFileType {
	public static final EvidentlyFileType INSTANCE = new EvidentlyFileType()
	
	new() {
		super(EvidentlyLanguage.INSTANCE)
	}
}
