/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlySemanticHighlightVisitor extends SemanticHighlightVisitor {
	public EvidentlySemanticHighlightVisitor() {
		EvidentlyLanguage.INSTANCE.injectMembers(this);
	}
}
