/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.evidently.idea.lang.EvidentlyLanguage;
import org.jetbrains.annotations.NotNull;

public class EvidentlySyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return EvidentlyLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
