/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlySemanticHighlightVisitor extends SemanticHighlightVisitor {
	public EvidentlySemanticHighlightVisitor() {
		EvidentlyLanguage.INSTANCE.injectMembers(this);
	}
}
