/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlyFacetType extends AbstractFacetType<EvidentlyFacetConfiguration> {

	public static final FacetTypeId<Facet<EvidentlyFacetConfiguration>> TYPEID = new FacetTypeId<Facet<EvidentlyFacetConfiguration>>("org.evidently.Evidently");

	public EvidentlyFacetType() {
		super(TYPEID, "org.evidently.Evidently", "Evidently");
		EvidentlyLanguage.INSTANCE.injectMembers(this);
	}
}
