/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.web;

import org.eclipse.xtext.xbase.web.DefaultXbaseWebModule;

/**
 * Manual modifications go to {@link EvidentlyWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEvidentlyWebModule extends DefaultXbaseWebModule {

}
