/*
 * generated by Xtext 2.12.0
 */
package org.evidently.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link EvidentlyWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEvidentlyWebModule extends DefaultWebModule {

}
