/**
 * generated by Xtext 2.12.0
 */
package org.evidently.validation;

import org.evidently.validation.AbstractEvidentlyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EvidentlyValidator extends AbstractEvidentlyValidator {
}
