/**
 * generated by Xtext 2.12.0
 */
package org.evidently.web;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class EvidentlyWebSetup /* implements EvidentlyStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nEvidentlyRuntimeModule cannot be resolved."
      + "\nEvidentlyIdeModule cannot be resolved.");
  }
}
