/**
 * generated by Xtext 2.12.0
 */
package org.evidently.web;

import org.evidently.web.AbstractEvidentlyWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class EvidentlyWebModule extends AbstractEvidentlyWebModule {
}
