/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.lang;

import org.evidently.idea.lang.AbstractEvidentlyFileType;

@SuppressWarnings("all")
public class EvidentlyFileType extends AbstractEvidentlyFileType {
  public final static EvidentlyFileType INSTANCE = new EvidentlyFileType();
  
  public EvidentlyFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(EvidentlyLanguage) is undefined");
  }
}
