/*
 * generated by Xtext 2.12.0
 */
package org.evidently.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.evidently.evidently.Model
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.evidently.evidently.Levels
import org.evidently.evidently.PolicyFile

@RunWith(XtextRunner)
@InjectWith(EvidentlyInjectorProvider)
class EvidentlyParsingTest {
	@Inject
	ParseHelper<PolicyFile> parseHelper
	
	@Test
	def void loadLevels() {
		val result = parseHelper.parse('''
		levels Android {
		
		    sink {
		          DISPLAY
		        , SPEAKER
		        , WRITE_CLIPBOARD
		        , WRITE_EMAIL
		        , WRITE_LOGS
		    }
		
		    source {
		          ACCELEROMETER
		        , BUNDLE
		        , MEDIA
		        , PHONE_NUMBER
		        , RANDOM
		        , READ_CLIPBOARD
		        , READ_EMAIL
		        , READ_TIME
		        , REFLECTION
		        , SENSOR
		        , USER_INPUT
		    }
		
		    both {
		          CAMERA_SETTINGS
		        , CONTENT_PROVIDER
		        , DATABASE
		        , FILESYSTEM
		        , INTENT
		        , PARCEL
		        , PROCESS_BUILDER
		        , SECURE_HASH
		        , SHARED_PREFERENCES
		        , SYSTEM_PROPERTIES
		    }
		}

		''')
		
		Assert.assertNotNull(result)
	}
}
