/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class EvidentlyFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
