/**
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.completion;

import org.evidently.idea.completion.AbstractEvidentlyCompletionContributor;

@SuppressWarnings("all")
public class EvidentlyCompletionContributor extends AbstractEvidentlyCompletionContributor {
  public EvidentlyCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor EvidentlyCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public EvidentlyCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
