/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EvidentlyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/evidently/idea/parser/antlr/internal/PsiInternalEvidently.tokens");
	}
}
