/*
 * generated by Xtext 2.12.0
 */
package org.evidently.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.evidently.EvidentlyRuntimeModule
import org.evidently.EvidentlyStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EvidentlyIdeSetup extends EvidentlyStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EvidentlyRuntimeModule, new EvidentlyIdeModule))
	}
	
}
