/*
 * generated by Xtext 2.12.0
 */
package org.evidently.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlyCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public EvidentlyCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(EvidentlyLanguage.INSTANCE, psiModificationTracker);
	}

}
