/*
 * Automatically generated by Evidently. DO NOT MODIFY. */
package org.evidently.idea.lang.psi;

import com.intellij.psi.impl.PsiTreeChangeEventImpl;
import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.evidently.idea.lang.EvidentlyLanguage;

public class EvidentlyCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public EvidentlyCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(EvidentlyLanguage.INSTANCE, psiModificationTracker);
	}
	protected boolean hasJavaStructuralChanges(PsiTreeChangeEventImpl event) {
		return true;
	}

}
