/*
 * generated by Xtext 2.12.0
 */
package org.evidently.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.evidently.parser.antlr.internal.InternalEvidentlyParser;
import org.evidently.services.EvidentlyGrammarAccess;

public class EvidentlyParser extends AbstractAntlrParser {

	@Inject
	private EvidentlyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEvidentlyParser createParser(XtextTokenStream stream) {
		return new InternalEvidentlyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EvidentlyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EvidentlyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
